CREATE TABLE if not exists Users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  login VARCHAR UNIQUE NOT NULL,
  name VARCHAR NOT NULL,
  birthday DATE NOT NULL
);

CREATE TABLE if not exists Users_friends (
  user_id INTEGER,
  friend_id INTEGER,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE if not exists Genres (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  genre_name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE if not exists MPA (
  mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  mpa_name VARCHAR UNIQUE
);

CREATE TABLE if not exists Films (
  film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  film_name VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  release_date DATE NOT NULL,
  duration INTEGER NOT NULL,
  rate INTEGER,
  mpa_id INTEGER NOT NULL
);

CREATE TABLE if not exists Film_likes (
  film_id INTEGER,
  user_id INTEGER,
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE if not exists Film_genre (
  film_id INTEGER,
  genre_id INTEGER,
  PRIMARY KEY (film_id, genre_id)
);

ALTER TABLE Users_friends ADD CONSTRAINT user_id_Users_user_id FOREIGN KEY (user_id) REFERENCES Users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Users_friends ADD CONSTRAINT friend_id_Users_user_id FOREIGN KEY (friend_id) REFERENCES Users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Films ADD CONSTRAINT mpa_id_MPA_mpa_id FOREIGN KEY (mpa_id) REFERENCES MPA (mpa_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_likes ADD CONSTRAINT Film_likes_film_id_Films_film_id FOREIGN KEY (film_id) REFERENCES Films (film_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_likes ADD CONSTRAINT Film_likes_user_id_Users_user_id FOREIGN KEY (user_id) REFERENCES Users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_genre ADD CONSTRAINT Film_genre_film_id_Films_film_id FOREIGN KEY (film_id) REFERENCES Films (film_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_genre ADD CONSTRAINT Film_genre_user_id_Users_user_id FOREIGN KEY (genre_id) REFERENCES Genres (genre_id) ON DELETE RESTRICT ON UPDATE CASCADE;