CREATE TABLE if not exists Users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  login VARCHAR UNIQUE NOT NULL,
  name VARCHAR NOT NULL,
  birthday DATE NOT NULL
);

CREATE TABLE if not exists Users_friends (
  proposer_id INTEGER,
  invited_id INTEGER,
  PRIMARY KEY (proposer_id, invited_id)
);

CREATE TABLE if not exists Genre (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  genre_name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE if not exists Rating (
  rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  rating_name VARCHAR UNIQUE
);

CREATE TABLE if not exists Films (
  film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  film_name VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  release_date DATE NOT NULL,
  duration INTEGER NOT NULL,
  rating_id INTEGER NOT NULL
);

CREATE TABLE if not exists Film_likes (
  film_id INTEGER,
  user_id INTEGER,
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE if not exists Film_genre (
  film_id INTEGER,
  genre_id INTEGER,
  PRIMARY KEY (film_id, genre_id)
);

ALTER TABLE Users_friends ADD CONSTRAINT proposer_id_Users_user_id FOREIGN KEY (proposer_id) REFERENCES Users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Users_friends ADD CONSTRAINT invited_id_Users_user_id FOREIGN KEY (invited_id) REFERENCES Users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Films ADD CONSTRAINT rating_id_Rating_rating_id FOREIGN KEY (rating_id) REFERENCES Rating (rating_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_likes ADD CONSTRAINT Film_likes_film_id_Films_film_id FOREIGN KEY (film_id) REFERENCES Films (film_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_likes ADD CONSTRAINT Film_likes_user_id_Users_user_id FOREIGN KEY (user_id) REFERENCES Users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_genre ADD CONSTRAINT Film_genre_film_id_Films_film_id FOREIGN KEY (film_id) REFERENCES Films (film_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Film_genre ADD CONSTRAINT Film_genre_user_id_Users_user_id FOREIGN KEY (genre_id) REFERENCES Genre (genre_id) ON DELETE RESTRICT ON UPDATE CASCADE;